import UiText from "../../ui/UiText.jsx";
import { useEffect, useState } from "react";
import { ingestionApi, filePayload } from "../../api/client.js";
import "../../styles/ingestion.css";
const FIELDS = ["activityId", "activityName", "wbs", "projectId", "discipline", "location", "plannedStart", "plannedEnd", "actualStart", "actualEnd", "plannedDuration", "actualDuration", "progress", "predecessors", "successors", "level", "parentActivityId", "teamId", "totalFloat"];

export default function ScheduleIngestion({ projectId, onReload }) {
  const [file, setFile] = useState(null), [mapping, setMapping] = useState({}), [preview, setPreview] = useState(null);
  const [versions, setVersions] = useState(null), [offset, setOffset] = useState(0), [before, setBefore] = useState(""), [after, setAfter] = useState("");
  const [diff, setDiff] = useState(null), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [revision, setRevision] = useState(0);
  useEffect(() => { let active = true; if (projectId) ingestionApi.versions(projectId, offset).then(r => { if (active) setVersions(r); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, [projectId, offset, revision]);
  async function run(action) { setBusy(true); setMessage(""); try { await action(); } catch (e) { setMessage(e.message); } finally { setBusy(false); } }
  if (!projectId) return null;
  return <section className="ingestion-panel" aria-label="Schedule ingestion">
    <h2><UiText>Schedule import and versions</UiText></h2><p><UiText>CSV or XLSX, up to 2,000 activities. Dates: YYYY-MM-DD or native Excel dates. Dependencies: ActivityID:FS:lagDays. Existing field evidence and actuals are preserved.</UiText></p>
    <label><UiText>Schedule file</UiText><input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e => { const chosen = e.target.files?.[0]; setPreview(null); setMapping({}); setDiff(null); if (chosen) run(async () => setFile(await filePayload(chosen))); }} /></label>
    <button type="button" disabled={!file || busy} onClick={() => run(async () => { const r = await ingestionApi.preview(projectId, { ...file, mapping }); setPreview(r); setMapping(r.mapping); })}><UiText>Preview schedule</UiText></button>
    {preview && <><h3><UiText>Column mapping</UiText></h3><div className="ingestion-fields">{preview.headers.map(h => <label key={h}>{h}<select value={mapping[h] ?? ""} onChange={e => { setMapping({ ...mapping, [h]: e.target.value }); setPreview({ ...preview, canImport: false }); }}><option value=""><UiText>Preserve unsupported column</UiText></option>{FIELDS.map(f => <option key={f}>{f}</option>)}</select></label>)}</div><p>{preview.accepted}<UiText> accepted · </UiText>{preview.rejected}<UiText> rejected</UiText></p><p>{preview.warnings.join(" · ")}</p>{preview.errors.map((e, i) => <p role="alert" key={i}><UiText>Row </UiText>{e.row ?? "graph"}: {e.errors.join("; ")}</p>)}<details><summary><UiText>Preview rows and changes</UiText></summary><pre>{JSON.stringify({ rows: preview.rows.slice(0, 20), changes: preview.changeSummary }, null, 2)}</pre></details><button type="button" disabled={!preview.canImport || busy} onClick={() => run(async () => { const r = await ingestionApi.commit(projectId, { ...file, mapping, previewChecksum: preview.checksum, expectedVersionId: preview.currentVersionId }); setPreview(null); setRevision(v => v + 1); setMessage(`Imported ${r.version.accepted} activities. Version ${r.version.id}.`); await onReload?.(); })}><UiText>Import validated schedule</UiText></button></>}
    <h3><UiText>Persisted versions</UiText></h3>{versions?.items.map(v => <p key={v.id}>{v.kind} · {v.filename} · {v.accepted}<UiText> activities · </UiText>{new Date(v.createdAt).toLocaleString()} <small>{v.id}</small></p>)}
    <div className="ingestion-fields"><label><UiText>Compare from</UiText><select value={before} onChange={e => setBefore(e.target.value)}><option value=""><UiText>Choose version</UiText></option>{versions?.items.map(v => <option key={v.id} value={v.id}>{v.filename} · {v.id}</option>)}</select></label><label><UiText>Compare to</UiText><select value={after} onChange={e => setAfter(e.target.value)}><option value=""><UiText>Choose version</UiText></option>{versions?.items.map(v => <option key={v.id} value={v.id}>{v.filename} · {v.id}</option>)}</select></label></div><button type="button" disabled={!before || !after || busy} onClick={() => run(async () => setDiff(await ingestionApi.compare(projectId, before, after)))}><UiText>Compare versions</UiText></button>{diff && <pre>{JSON.stringify(diff, null, 2)}</pre>}
    <nav aria-label="Schedule version pages"><button disabled={!offset || busy} onClick={() => setOffset(Math.max(0, offset - 50))}><UiText>Previous versions</UiText></button><button disabled={!versions || offset + 50 >= versions.total || busy} onClick={() => setOffset(offset + 50)}><UiText>Next versions</UiText></button></nav>{message && <p role="status">{message}</p>}
  </section>;
}
