import UiText from "../../ui/UiText.jsx";
import { useState, useEffect } from "react";
import { ingestionApi } from "../../api/client.js";
import "../../styles/ingestion.css";
export default function SystemHealth({ onReload }) {
  const [status, setStatus] = useState(null), [name, setName] = useState(""), [location, setLocation] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; ingestionApi.system().then(r => { if (active) setStatus(r); }).catch(e => { if (active) setMessage(e.message); }); return () => { active = false; }; }, []);
  return <section className="ingestion-panel"><h2><UiText>System health</UiText></h2>{status && <><p><UiText>Database: </UiText>{status.database}<UiText> · Migrations: </UiText>{status.migrations}<UiText> · Rate limiting: </UiText>{status.rateLimitBackend}</p><p><UiText>OCR: </UiText>{status.providers.ocr}<UiText> · Speech: </UiText>{status.providers.asr}<UiText> · Advanced AI: </UiText>{status.providers.advanced}</p><p><UiText>Assistant chat: </UiText>{status.providers.chat ?? "NOT_CONFIGURED"}<UiText> (configuration only; live inference is checked separately).</UiText></p><p><UiText>Backup status: </UiText>{status.backupStatus}<UiText>. Restore verification is an operator responsibility.</UiText></p></>}<h3><UiText>Create project</UiText></h3><form onSubmit={async e => { e.preventDefault(); setBusy(true); try { const r = await ingestionApi.createProject({ name, location }); setMessage(`Created ${r.project.name}. Assign a Project Manager and team in Assignments.`); setName(""); await onReload?.(); } catch (failure) { setMessage(failure.message); } finally { setBusy(false); } }}><div className="ingestion-fields"><label><UiText>Project name</UiText><input required maxLength={120} value={name} onChange={e => setName(e.target.value)} /></label><label><UiText>Project location</UiText><input maxLength={120} value={location} onChange={e => setLocation(e.target.value)} /></label></div><button disabled={busy || !name.trim()}><UiText>Create project</UiText></button></form>{message && <p role="status">{message}</p>}</section>;
}
