"""Phase 7 parity and regression tests; fixtures were generated by the old JS API."""

from copy import deepcopy
import json
from pathlib import Path
import re

import pytest

from backend.app.services.activity_extractor import extract_field_activity, extract_identifiers
from backend.app.services.confidence import confidence_level, calculate_confidence
from backend.app.services.matching_service import analyze_field_activity, MATCHER_VERSION
from backend.app.services import workflow_service as workflow

GOLDEN = json.loads((Path(__file__).parent / "fixtures" / "phase7_parity.json").read_text(encoding="utf-8"))
VARIANTS = json.loads((Path(__file__).parent / "fixtures" / "phase7_variants.json").read_text(encoding="utf-8"))
NOW = GOLDEN["now"]
PIPING = GOLDEN["analyses"][0]["schedule"][0]


def analyze(text, schedules=None, context=None):
    return analyze_field_activity(text, [PIPING] if schedules is None else schedules, {"projectId": "TEST-PROJECT", "generatedAt": NOW, **(context or {})})


def normalize_generated_ids(value):
    """Only generated IDs differ intentionally: UUIDs replace timestamp IDs."""
    if isinstance(value, dict):
        return {key: ("GENERATED-REVIEW" if key == "id" and isinstance(item, str) and re.match(r"^REV-(?:\d{7,}|[0-9a-f]{8}-)", item) else "GENERATED-ORG-EVENT" if key == "id" and isinstance(item, str) and re.match(r"^ORG-ACT-(?:\d{7,}|[0-9a-f]{8}-)", item) else normalize_generated_ids(item)) for key, item in value.items()}
    if isinstance(value, list):
        return [normalize_generated_ids(item) for item in value]
    return value


def assert_golden(actual, expected):
    assert normalize_generated_ids(actual) == normalize_generated_ids(expected)


def submit():
    return workflow.submit_field_update(GOLDEN["seed"], GOLDEN["form"], GOLDEN["context"])


def match_for(data, update_id="TEST-UPDATE"):
    return next(item for item in data["activityMatches"] if item["fieldUpdateId"] == update_id)


def schedule_for(data, schedule_id):
    return next(item for item in data["scheduleActivities"] if item["id"] == schedule_id)


def test_identifiers_normalize_without_merging_distinct_tags():
    assert extract_identifiers(GOLDEN["identifiers"]["text"]) == GOLDEN["identifiers"]["result"]
    assert "P-0101" != "P-101"


@pytest.mark.parametrize("example", GOLDEN["extraction"], ids=lambda item: item["text"])
def test_original_javascript_extraction_parity(example):
    assert extract_field_activity(example["text"]) == example["result"]


@pytest.mark.parametrize("case", GOLDEN["analyses"], ids=lambda item: item["name"])
def test_original_javascript_matching_evidence_parity(case):
    assert analyze(case["text"], case["schedule"], case["context"]) == case["result"]


@pytest.mark.parametrize("case", VARIANTS["rows"], ids=lambda item: item["text"])
def test_original_javascript_combinations_parity(case):
    assert analyze(case["text"], VARIANTS["schedules"]) == case["result"]


def test_all_infrastructure_disciplines_remain_supported():
    for text, discipline in [("Rebar installed", "Civil"), ("Flange installed", "Piping"), ("Mechanical equipment insulation", "Mechanical"), ("Vessel installed", "Static Equipment"), ("Motor installed", "Rotating Equipment"), ("Earthing completed", "Electrical"), ("Junction box installed", "Instrumentation"), ("Safety permit inspection", "HSE")]:
        assert extract_field_activity(text)["discipline"] == discipline


def test_reported_progress_date_references_and_negated_completion():
    result = extract_field_activity("Cable tray 65% complete in Block 3 on 2026-10-04; remaining work tomorrow")
    assert result["progress"] == 65
    assert result["dateReferences"] == ["2026-10-04", "tomorrow"]
    assert extract_field_activity("Cable tray not completed in Block 3")["completion"] is False


@pytest.mark.parametrize("description, explicit_progress", [
    ("Spool erection is 30 percent complete for Line 247-XX", None),
    ("Spool erection 65% complete for Line 247-XX", None),
    ("Spool erection completed for Line 247-XX", 45),
])
def test_partial_progress_does_not_create_completion_actual(description, explicit_progress):
    form = {"description": description, "activityId": "SA-1024"}
    if explicit_progress is not None:
        form["progress"] = explicit_progress
    result = workflow.submit_field_update(GOLDEN["seed"], form, GOLDEN["context"])
    update = result["fieldUpdates"][0]
    assert 0 < update["progress"] < 100
    assert update["actualEnd"] is None
    confirmed = workflow.confirm_match(result, {**GOLDEN["opts"], "scheduleActivityId": "SA-1024"})
    assert not confirmed.get("error")
    activity = schedule_for(confirmed["data"], "SA-1024")
    assert activity["actualEnd"] is None
    assert activity["status"] == "In Progress"


def test_edit_reducing_progress_clears_the_previous_completion_actual():
    result = workflow.submit_field_update(GOLDEN["seed"], {"description":"Spool erection completed for Line 247-XX", "activityId":"SA-1024", "progress":100}, GOLDEN["context"])
    update = result["fieldUpdates"][0]
    assert update["actualEnd"] == NOW
    update.update(progress=40, rawText="Spool erection 40 percent complete for Line 247-XX")
    rematched = workflow.rematch_field_update(result, update["id"], GOLDEN["rematchContext"])
    assert not rematched.get("error")
    edited = next(row for row in rematched["data"]["fieldUpdates"] if row["id"] == update["id"])
    assert edited["actualEnd"] is None
    confirmed = workflow.confirm_match(rematched["data"], {**GOLDEN["opts"], "scheduleActivityId":"SA-1024"})
    assert not confirmed.get("error")
    assert schedule_for(confirmed["data"], "SA-1024")["status"] == "In Progress"


def test_exact_identifier_and_strong_activity_are_high():
    match = analyze("Spool erected for Line 247-XX near compressor area")["match"]
    assert match["recommendedMatchId"] == PIPING["id"]
    assert match["confidenceLevel"] == "high"
    assert match["confidence"] == 100
    assert match["recommendationStatus"] == "suggested"


def test_activity_similarity_without_identifier():
    schedule = {**PIPING, "activityName": "Install cable tray in Substation A", "discipline": "Electrical", "location": "Substation A"}
    match = analyze("Cable tray installation completed in Substation A", [schedule])["match"]
    assert match["recommendedMatchId"] == schedule["id"]
    assert any(item["signal"] == "activity" and item["outcome"] == "support" for item in match["evidence"])
    assert any(item["signal"] == "identifier" and item["outcome"] == "missing" for item in match["evidence"])


def test_discipline_mismatch_reduces_confidence_and_is_explained():
    text = "Spool erected for Line 247-XX near compressor area"
    compatible = analyze(text)["match"]
    incompatible = analyze(text, [{**PIPING, "discipline": "Electrical"}])["match"]
    assert incompatible["confidence"] < min(60, compatible["confidence"])
    assert any(item["signal"] == "discipline" and item["outcome"] == "conflict" for item in incompatible["evidence"])


def test_location_match_conflict_and_missing_are_distinct():
    exact = analyze("Spool erected for Line 247-XX near compressor area")["match"]
    conflict = analyze("Spool erected for Line 247-XX in Substation A")["match"]
    missing = analyze("Spool erected for Line 247-XX")["match"]
    assert exact["confidence"] > conflict["confidence"]
    assert exact["confidence"] > missing["confidence"]
    for match, outcome in [(exact, "support"), (conflict, "conflict"), (missing, "missing")]:
        assert any(item["signal"] == "location" and item["outcome"] == outcome for item in match["evidence"])


def test_ambiguous_candidates_need_pm_selection():
    match = analyze("Spool erected for Line 247-XX near compressor area", [PIPING, {**PIPING, "id": "TEST-SECOND", "activityId": "TEST-002"}])["match"]
    assert match["recommendationStatus"] == "ambiguous"
    assert match["recommendedMatchId"] is None
    assert len(match["candidates"]) == 2
    assert "Multiple plausible activities have close scores" in match["unmatchReason"]


def test_conflicting_full_identifiers_cannot_be_high():
    match = analyze("Spool erected for Line 247-YY near compressor area")["match"]
    assert match["confidence"] < 60
    assert match["recommendedMatchId"] is None
    assert any(item["signal"] == "identifier" and item["outcome"] == "conflict" for item in match["evidence"])


def test_partial_identifiers_explain_missing_suffixes_and_are_capped():
    match = analyze("Spool erected for Line 247 near compressor area")["match"]
    assert match["confidence"] < 80
    assert any(item["signal"] == "identifier" and item["outcome"] == "partial" for item in match["evidence"])


def test_unknown_activity_why_not_is_data_derived():
    match = analyze("Lunch delivered to the site office")["match"]
    assert match["confidence"] == 0
    assert match["recommendedMatchId"] is None
    assert match["recommendationStatus"] == "unmatched"
    assert match["candidates"] == []
    assert "No project schedule activity" in match["unmatchReason"]


def test_fuzzy_terms_support_messy_wording():
    match = analyze("Spool errected for Line 247-XX near compressor area")["match"]
    assert match["recommendedMatchId"] == PIPING["id"]
    assert "Identifier matched" in match["matchReason"]


def test_other_projects_and_schedule_levels_are_excluded():
    match = analyze("Spool erected for Line 247-XX", [{**PIPING, "projectId": "OTHER-PROJECT"}, {**PIPING, "id": "OTHER-LEVEL", "level": "L4"}])["match"]
    assert match["candidates"] == []


def test_deterministic_order_independent_versioned_and_timestamped():
    schedules = [PIPING, {**PIPING, "id": "TEST-SECOND", "activityName": "Fit-up Line 247-XX joints"}]
    first = analyze("Spool erected for Line 247-XX", schedules)
    assert first == analyze("Spool erected for Line 247-XX", schedules[::-1])
    assert first["match"]["matcherVersion"] == MATCHER_VERSION
    assert first["match"]["generatedAt"] == NOW


def test_confidence_bands_and_javascript_rounding():
    assert [confidence_level(score) for score in (0, 59, 60, 79, 80, 100)] == ["low", "low", "medium", "medium", "high", "high"]
    signals = {key: {"available": True, "similarity": 0} for key in ("activity", "identifier", "discipline", "location", "keywords")}
    signals["activity"]["similarity"] = .6125
    assert calculate_confidence(signals)["score"] == 25


def test_submission_has_no_approval_or_actual_contribution_and_matches_js():
    result = submit()
    assert_golden(result, GOLDEN["submitted"])
    match = match_for(result)
    assert match["matchStatus"] == "review_required"
    assert match["matchedBy"] is None
    assert result["scheduleActivityContributions"] == GOLDEN["seed"]["scheduleActivityContributions"]
    assert result["fieldUpdates"][0]["reviewHistory"][1]["actorUserId"] is None


def test_confirm_change_unmatch_reconfirm_preserve_intelligence_and_reconcile():
    result = submit()
    initial_match = deepcopy(match_for(result))
    result = workflow.confirm_match(result, {**GOLDEN["opts"], "scheduleActivityId": "SA-1024"})
    assert_golden(result, GOLDEN["confirmed"])
    assert schedule_for(result["data"], "SA-1024")["progress"] == 40
    result = workflow.change_match(result["data"], {**GOLDEN["opts"], "scheduleActivityId": "SA-1031"})
    assert_golden(result, GOLDEN["changed"])
    assert schedule_for(result["data"], "SA-1024")["progress"] == 65
    assert schedule_for(result["data"], "SA-1031")["progress"] == 40
    result = workflow.mark_unmatched(result["data"], {**GOLDEN["opts"], "reason": "Wrong scope", "feedback": "Please check"})
    assert_golden(result, GOLDEN["unmatched"])
    assert schedule_for(result["data"], "SA-1031")["progress"] == result["data"]["scheduleActivityBaselines"]["SA-1031"]["progress"]
    assert not any(item["fieldUpdateId"] == "TEST-UPDATE" for item in result["data"]["scheduleActivityContributions"])
    result = workflow.confirm_match(result["data"], {**GOLDEN["opts"], "scheduleActivityId": "SA-1031"})
    assert_golden(result, GOLDEN["reconfirmed"])
    match = match_for(result["data"])
    assert match["candidates"] == initial_match["candidates"]
    assert match["matchedByUserId"] == "PM-001"
    assert any(item["fieldUpdateId"] == "FU-1042" for item in result["data"]["scheduleActivityContributions"])


def test_edit_rematches_resets_review_and_preserves_unrelated_contributions():
    result = workflow.rematch_field_update(GOLDEN["editedInput"], "TEST-UPDATE", GOLDEN["rematchContext"])
    assert_golden(result, GOLDEN["rematched"])
    match = match_for(result["data"])
    assert match["recommendedMatchId"] == "SA-1031"
    assert match["matchedByUserId"] is None
    assert match["generatedAt"] == "2026-10-04T09:00:00.000Z"
    update = next(item for item in result["data"]["fieldUpdates"] if item["id"] == "TEST-UPDATE")
    assert update["reviewHistory"][-1]["actorUserId"] == "TL-001"
    assert result["data"]["scheduleActivityContributions"] == GOLDEN["seed"]["scheduleActivityContributions"]


def test_request_information_retains_link_and_contribution():
    result = workflow.request_information(GOLDEN["confirmed"]["data"], {**GOLDEN["opts"], "feedback": "Please confirm reported time"})
    assert_golden(result, GOLDEN["feedback"])
    assert result["shouldClose"] is False
    assert result["data"]["scheduleActivityContributions"] == GOLDEN["confirmed"]["data"]["scheduleActivityContributions"]


@pytest.mark.parametrize("case", GOLDEN["actions"], ids=lambda item: item["action"])
def test_assigned_activity_actions_preserve_phase6_actuals(case):
    assert_golden(getattr(workflow, case["action"] + "_activity")(GOLDEN["seed"], case["options"]), case["result"])


def test_integral_float_progress_preserves_javascript_history_wording():
    case = next(item for item in GOLDEN["actions"] if item["action"] == "update")
    options = deepcopy(case["options"])
    options["details"]["progress"] = 45.0
    assert_golden(workflow.update_activity(GOLDEN["seed"], options), case["result"])


@pytest.mark.parametrize("case", GOLDEN["assignments"], ids=lambda item: item["action"])
def test_assignment_mutators_preserve_schedule_ownership_and_js_contract(case):
    assert_golden(getattr(workflow, "assign_" + case["action"])(GOLDEN["seed"], {**case["options"], "now": NOW}), case["result"])


def test_mutators_never_modify_caller_input():
    original = deepcopy(GOLDEN["seed"])
    submitted = submit()
    workflow.confirm_match(submitted, {**GOLDEN["opts"], "scheduleActivityId": "SA-1024"})
    for case in GOLDEN["actions"]:
        workflow.record_activity_action(GOLDEN["seed"], case["options"])
    assert GOLDEN["seed"] == original
    assert_golden(submitted, GOLDEN["submitted"])


def test_invalid_completed_and_cross_project_reviews_fail_without_changes():
    result = submit()
    invalid = workflow.confirm_match(result, {**GOLDEN["opts"], "scheduleActivityId": "MISSING"})
    assert invalid["error"] == "The selected schedule activity could not be found."
    result["scheduleActivities"].append({**PIPING, "id": "OTHER-PROJECT-ACTIVITY"})
    invalid = workflow.confirm_match(result, {**GOLDEN["opts"], "scheduleActivityId": "OTHER-PROJECT-ACTIVITY"})
    assert invalid["error"] == "The selected schedule activity belongs to a different project."
    result["fieldUpdates"][0]["progress"] = 100
    invalid = workflow.confirm_match(result, {**GOLDEN["opts"], "scheduleActivityId": "SA-1024"})
    assert invalid["error"] == "Actual completion time is required before confirming this update."
    assert invalid["data"] == result


def test_review_uuid_uniqueness_and_request_review_idempotence():
    first, second = submit(), submit()
    assert first["reviewItems"][0]["id"] != second["reviewItems"][0]["id"]
    assert re.fullmatch(r"REV-[0-9a-f-]{36}", first["reviewItems"][0]["id"])
    requested = workflow.request_planner_review(first, "TEST-UPDATE", {"reviewer": "Priya", "reviewerUserId": "PM-001"})
    assert requested == first


def test_legacy_enrichment_preserves_decisions_history_baseline_and_actuals():
    seed = GOLDEN["seed"]
    result = workflow.enrich_match_intelligence(seed, NOW)
    assert result == seed
    assert result is not seed


def test_invalid_submission_and_action_inputs_do_not_change_workspace():
    for progress in (-1, 101, float("nan"), True, "20"):
        assert workflow.submit_field_update(GOLDEN["seed"], {"description": "Spool erected", "progress": progress}, GOLDEN["context"]) == GOLDEN["seed"]
    assert workflow.submit_field_update(GOLDEN["seed"], {"description": " ", "progress": 40}, GOLDEN["context"]) == GOLDEN["seed"]
    assert workflow.block_activity(GOLDEN["seed"], {"activityId": "TL-2002", "details": {"blockedReason": " "}}) == GOLDEN["seed"]
