"""Phase 10 organization and departmental workflows; preserve prior data."""
from alembic import op
import sqlalchemy as sa

revision = "0004_organization"
down_revision = "0003_schedule_ingestion"
branch_labels = None
depends_on = None

def upgrade():
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.create_check_constraint('ck_users_role', 'users', "role IN ('ADMIN','PROJECT_MANAGER','TEAM_LEADER','WORKFORCE','DEPARTMENT')")
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_department_name')
    )
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_table('designations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designations_organization_id'), 'designations', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('materials',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_organization_id'), 'materials', ['organization_id'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('discipline', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_organization_id'), 'skills', ['organization_id'], unique=False)
    op.create_table('vendors',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_organization_id'), 'vendors', ['organization_id'], unique=False)
    op.create_table('client_contacts',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_contacts_organization_id'), 'client_contacts', ['organization_id'], unique=False)
    op.create_table('department_grants',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('capability', sa.Text(), nullable=False),
    sa.Column('granted_by', sa.Text(), nullable=False),
    sa.CheckConstraint("capability IN ('business','materials','people','quality','hse','hr-confidential')", name='ck_department_capability'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'capability')
    )
    op.create_table('department_units',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Text(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_units_organization_id'), 'department_units', ['organization_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_table('project_departments',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'department_id')
    )
    op.create_table('stores',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('location_id', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_organization_id'), 'stores', ['organization_id'], unique=False)
    op.create_table('employees',
    sa.Column('workforce_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Text(), nullable=False),
    sa.Column('unit_id', sa.Text(), nullable=True),
    sa.Column('designation_id', sa.Text(), nullable=True),
    sa.Column('location_id', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Text(), nullable=True),
    sa.Column('account_id', sa.Text(), nullable=True),
    sa.Column('discipline', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['department_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('organization_id', 'workforce_code', name='uq_employee_code')
    )
    op.create_index('idx_employee_org_department', 'employees', ['organization_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_table('safety_events',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_events_organization_id'), 'safety_events', ['organization_id'], unique=False)
    op.create_table('tenders',
    sa.Column('opportunity_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_organization_id'), 'tenders', ['organization_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('skill_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'skill_id')
    )
    op.create_table('inspections',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=True),
    sa.Column('activity_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_organization_id'), 'inspections', ['organization_id'], unique=False)
    op.create_table('material_requests',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=True),
    sa.Column('activity_id', sa.Text(), nullable=True),
    sa.Column('material_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('required_on', sa.Date(), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_material_request_quantity'),
    sa.ForeignKeyConstraint(['activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_requests_organization_id'), 'material_requests', ['organization_id'], unique=False)
    op.create_table('people_records',
    sa.Column('employee_id', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('team_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('confidential', sa.Boolean(), nullable=False),
    sa.Column('start_on', sa.Date(), nullable=False),
    sa.Column('end_on', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.CheckConstraint("confidential = (kind IN ('grievance','wellbeing','employee-relations','performance'))", name='ck_people_privacy'),
    sa.CheckConstraint('end_on IS NULL OR end_on >= start_on', name='ck_people_dates'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_records_organization_id'), 'people_records', ['organization_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('responsibility', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'employee_id')
    )
    op.create_table('proposals',
    sa.Column('tender_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_organization_id'), 'proposals', ['organization_id'], unique=False)
    op.create_table('workforce_assignments',
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('effective_start', sa.Date(), nullable=False),
    sa.Column('effective_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('assigned_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','ENDED')", name='ck_workforce_status'),
    sa.CheckConstraint('effective_end IS NULL OR effective_end >= effective_start', name='ck_workforce_dates'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workforce_project_team', 'workforce_assignments', ['organization_id', 'project_id', 'team_id'], unique=False)
    op.create_index(op.f('ix_workforce_assignments_organization_id'), 'workforce_assignments', ['organization_id'], unique=False)
    op.create_index('uq_workforce_active', 'workforce_assignments', ['employee_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('commercial_contracts',
    sa.Column('proposal_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_commercial_contracts_organization_id'), 'commercial_contracts', ['organization_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('vendor_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['material_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_purchase_orders_organization_id'), 'purchase_orders', ['organization_id'], unique=False)
    op.create_table('quality_issues',
    sa.Column('inspection_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issues_organization_id'), 'quality_issues', ['organization_id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('quality_issue_id', sa.Text(), nullable=True),
    sa.Column('safety_event_id', sa.Text(), nullable=True),
    sa.Column('assigned_employee_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.CheckConstraint('(quality_issue_id IS NOT NULL) <> (safety_event_id IS NOT NULL)', name='ck_action_source'),
    sa.ForeignKeyConstraint(['assigned_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['quality_issue_id'], ['quality_issues.id'], ),
    sa.ForeignKeyConstraint(['safety_event_id'], ['safety_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_organization_id'), 'corrective_actions', ['organization_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipts_organization_id'), 'goods_receipts', ['organization_id'], unique=False)
    op.create_table('material_movements',
    sa.Column('material_id', sa.Text(), nullable=False),
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=True),
    sa.Column('receipt_id', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('organization_id', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('RECEIPT','ISSUE')", name='ck_material_movement_kind'),
    sa.CheckConstraint('quantity > 0', name='ck_material_movement_quantity'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    op.create_index(op.f('ix_material_movements_organization_id'), 'material_movements', ['organization_id'], unique=False)
    op.add_column('users', sa.Column('login_id', sa.Text(), nullable=True))
    op.create_check_constraint('ck_login_identifier', 'users', "login_id IS NULL OR login_id ~ '^[a-zA-Z0-9][a-zA-Z0-9._-]{2,79}$'")
    op.create_index('uq_users_login_lower', 'users', [sa.literal_column('lower(login_id)')], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # Downgrades refuse new account roles instead of silently deleting/converting them.
    op.drop_constraint('ck_users_role', 'users', type_='check')
    op.create_check_constraint('ck_users_role', 'users', "role IN ('ADMIN','PROJECT_MANAGER','TEAM_LEADER')")
    op.drop_constraint('ck_login_identifier', 'users', type_='check')
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_login_lower', table_name='users')
    op.drop_column('users', 'login_id')
    op.drop_index(op.f('ix_material_movements_organization_id'), table_name='material_movements')
    op.drop_table('material_movements')
    op.drop_index(op.f('ix_goods_receipts_organization_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_corrective_actions_organization_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_quality_issues_organization_id'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_purchase_orders_organization_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_commercial_contracts_organization_id'), table_name='commercial_contracts')
    op.drop_table('commercial_contracts')
    op.drop_index('uq_workforce_active', table_name='workforce_assignments', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_workforce_assignments_organization_id'), table_name='workforce_assignments')
    op.drop_index('idx_workforce_project_team', table_name='workforce_assignments')
    op.drop_table('workforce_assignments')
    op.drop_index(op.f('ix_proposals_organization_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_people_records_organization_id'), table_name='people_records')
    op.drop_table('people_records')
    op.drop_index(op.f('ix_material_requests_organization_id'), table_name='material_requests')
    op.drop_table('material_requests')
    op.drop_index(op.f('ix_inspections_organization_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_tenders_organization_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_safety_events_organization_id'), table_name='safety_events')
    op.drop_table('safety_events')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index('idx_employee_org_department', table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_stores_organization_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('project_departments')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_department_units_organization_id'), table_name='department_units')
    op.drop_table('department_units')
    op.drop_table('department_grants')
    op.drop_index(op.f('ix_client_contacts_organization_id'), table_name='client_contacts')
    op.drop_table('client_contacts')
    op.drop_index(op.f('ix_vendors_organization_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_skills_organization_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_materials_organization_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_designations_organization_id'), table_name='designations')
    op.drop_table('designations')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
